config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('blog_posts')

  get 'blog_posts', to: 'blog_posts#index', as: 'blog_posts'
  post 'blog_posts', to: 'blog_posts#create'
  get 'blog_posts/new', to: 'blog_posts#new', as: 'new_blog_post'
  get 'blog_posts/:id', to: 'blog_posts#show', as: 'blog_post'
  get 'blog_posts/:id/edit', to: 'blog_posts#edit', as: 'edit_blog_post'
  patch 'blog_posts/:id', to: 'blog_posts#update'
  delete 'blog_posts/:id', to: 'blog_posts#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.order(created_at: :desc)
    render :index
  end

  def show
    @blog_post = BlogPost.find(params[:id])
    render :show
  end

  def new
    @blog_post = BlogPost.new
    render :new
  end

  def create
    @blog_post = BlogPost.new(params.require(:blog_post).permit(:title, :body))
    if @blog_post.save
      flash[:success] = 'Blog post was successfully created.'
      redirect_to blog_post_path(@blog_post)
    else
      flash.now[:error] = 'Unable to create blog post.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
    render :edit
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(params.require(:blog_post).permit(:title, :body))
      flash[:success] = 'Blog post was successfully updated.'
      redirect_to blog_post_path(@blog_post)
    else
      flash.now[:error] = 'Unable to update blog post.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    flash[:success] = 'Blog post was successfully destroyed.'
    redirect_to blog_posts_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/edit.html.erb
<h1 class="my-4">Editing Blog Post</h1>

<%= bootstrap_form_with model: @blog_post, url: blog_post_path(@blog_post), method: :patch, data: { turbo: false } do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body, rows: 16 %>
  <%= form.submit class: 'btn btn-primary my-3' %>
<% end %>

<p>
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/blog_posts/index.html.erb
<h1 class="my-4">Latest Blog Posts</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">

    <tbody>
      <% @blog_posts.each do |blog_post| %>
        <tr>
          <td><%= blog_post.title %></td>
          <td>TODO_AUTHOR</td>
          <td class="text-nowrap">
            <%= link_to 'Read', blog_post_path(blog_post), class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-primary btn-sm' %>
            <%= button_to 'Delete', blog_post_path(blog_post), method: :delete, data: { turbo: false }, class: 'btn btn-primary btn-sm', form: { class: 'd-inline' } %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

<p>
  <%= link_to 'New Blog Post', new_blog_post_path, class: 'btn btn-primary my-3' %>
</p>

app/views/blog_posts/new.html.erb
<h1 class="my-4">New Blog Post</h1>

<%= bootstrap_form_with model: @blog_post, url: blog_posts_path, method: :post, data: { turbo: false } do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body, rows: 16 %>
  <%= form.submit class: 'btn btn-primary my-3' %>
<% end %>

<p>
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/blog_posts/show.html.erb
<h1 class="my-4"><%= @blog_post.title %></h1>

<p>
  By TODO_AUTHOR
</p>

<%= simple_format(@blog_post.body) %>

<p class="mt-4">
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container text-end my-1">
      <%= link_to 'TODO_LINK', nil, class: 'btn btn-outline-primary btn-sm' %>
    </div>
    <%= render 'shared/flash' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>